[package]
name = "tch-serde"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
tch = "0.1"
serde = { version = "1.0", features = ["derive"] }
half = { version = "1.6", features = ["serde"] }

[dev-dependencies]
anyhow = "1.0"
serde_json = "1.0"
